### ISSUE TITLE
Returned Image is just noise

### ISSUE THREAD

**Issue by JasonTheC** [kelu124/pyusbus#1]
Hello, thanks for this repo!

I'm just getting noise when running getImages on a UP20. The noise looks like US noise with the different depth level resolutions, but it's still just noise, any tips on getting an actual image?
![test](https://user-images.githubusercontent.com/35046081/136939767-2b0538a1-7b7f-46da-a225-a7ce72113b61.png)

**Comment by mm80843** [comment]
Hi @CarrierDiagnostics  - just saw this message. Are you using some gel? 
At a first glance, I'd say couplant could be an issue, then it is also possibly an issue of setting the right gain.

**Comment by JasonTheC** [comment]
I switched to Ubuntu and it sort of worked. This was a while ago and have abandoned trying to use this code. Thanks for your input.

**Comment by logloimic** [comment]
Hi @kelu124, thanks for your work on this. I am having the same issues as CarrierDiagnostics. So far, I have ruled out couplant as an issue (tested in water, which gave clean signals on the Healson's Windows app). Unfortunately, the issue did not go away when tested on Ubuntu. My theory is that certain pre-processing steps have not been performed by my probe, as these images look like when I undo all processing adjustments on the Healson app (Gains, SmartSRI, Dynamic range etc). Would you have any recommendations on how to adjust the Gains? 

Thanks so much in advance.

**Comment by kelu124** [comment]
Hi @logloimic ! To help with the request - is this too an UP20 probe? 
I have noted that most of the processing is done on the phone (expect possibly for gain).
Could you please share images/signals?

**Comment by logloimic** [comment]
Thanks for your reply @kelu124! It is also an UP20L probe. 

Here are some examples: 
* Example 1:
![image](https://github.com/kelu124/pyusbus/assets/151602960/16c17fe0-79de-4705-8349-304fbef2fd2d)

* Example 2: Some structures can be seen at the top (however, not consistent with what I expected)
![image](https://github.com/kelu124/pyusbus/assets/151602960/2398c394-1454-477a-bb22-d92aa6ddfac8)

For the second example, you can see that the horizontal resolution at the top (y < 80) is double that of the bottom. Could be a refresh rate problem?

I have tried averaging several acquisitions together, but still cannot get useful structural information.

Here is what I'd expect the images to look like (acquired on the same computer with the Healson application)
![IMG_4945 w:250](https://github.com/kelu124/pyusbus/assets/151602960/62edbc15-2dc8-41c0-9d88-0ccc0fb6f55f)

Sample noisy acquisition:
[ex_gh.txt](https://github.com/kelu124/pyusbus/files/13494003/ex_gh.txt)

Edited to add: From the log file after running Healson app:

```
Timestamp1: H_DataRW::device_getImage---start(163840) # Which I guess indicates 2 bytes, consistent with your codes
Timestamp2: H_DataRW::device_getImage---end(1)

```
